version: "3.7"
services:
  mongo:
    container_name: mongo-container
    image: mongo:3
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  server:
    container_name: blogNode
    build: .
    environment:
      - PORT=3001
      - MONGO_URL=mongodb://mongo:27017/blog-node
    volumes:
      - .:/usr/src/blog-node
      - ./package.json:/usr/src/blog-node/package.json
    restart: always
    ports:
      - "3001:3001"
    links:
      - mongo
